---
name: Dev Build & Deploy Tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.platform/**'
  workflow_dispatch:

jobs:
  build_and_tag:
    name: Build & Tag
    uses: nax-platform/github-actions/.github/workflows/cut-tag-maven-service.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

  deploy_tag_dev:
    name: Deploy Tag to dev
    needs: build_and_tag
    uses: nax-platform/github-actions/.github/workflows/promote-tag-with-digest.yaml@main
    with:
      target-env: dev
      tag: ${{ needs.build_and_tag.outputs.tag_name }}
    secrets:
      TOKEN: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
