name: Mirror to nax-tech

on:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository_owner == 'nax-platform'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@v0.7.0
          with:
            REMOTE: 'https://github.com/nax-tech/github-actions.git'
            GIT_USERNAME: cnuss
            GIT_PASSWORD: ${{ secrets.NAX_TECH_PAT }}
