name: DEV Environment Build

on:
  workflow_call:
    inputs:
      source_providers:
        type: string
        description: >
          A comma-separated list (no spaces) of Artifact Storage providers to use for this workflow.
          Valid options are artifactory, cloudsmith. If not specified, defaults to artifactory.
        required: false
        default: artifactory
      destination_provider:
        type: string
        description: >
          A value indicating which Artifact Storage provider is the "primary" (i.e. where will packages be deployed).
          Be aware that the destination_provider must also be in the list of source_providers. Default is artifactory.
        required: false
        default: artifactory
      cloudsmith_service_account:
        type: string
        description: >
          The name of the Cloudsmith service account to use for accessing to Cloudsmith.
          Required if cloudsmith is specified in the providers input.
        required: false
        default: ${{ github.repository_owner }}-ci
    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_IDENTITY_TOKEN:
        required: true

jobs:
  build_and_publish_snapshots:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: naxgrp.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}

      # Set up Cloudsmith environment variables if necessary
      - name: Login to Cloudsmith if necessary
        if: contains(inputs.source_providers, 'cloudsmith')
        uses: nax-platform/cloudsmith-login@v2
        with:
          slug: ${{ inputs.cloudsmith_service_account }}
          namespace: nax-group

      - name: Configure Maven
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_IDENTITY_TOKEN: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
        run: |
          mkdir -p $HOME/.m2
          touch $HOME/.m2/settings.xml
          env | grep 'CLOUDSMITH\|ARTIFACTORY' | tee $RUNNER_TEMP/env.txt
          docker run -v $HOME/.m2:/root/.m2 --env-file $RUNNER_TEMP/env.txt naxgrp.jfrog.io/nax-platform-docker/applications/nax-cli:0.1.3 context -o $GITHUB_REPOSITORY_OWNER -p ${{ inputs.source_providers }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
          overwrite-settings: false

      - name: If not main branch, append branch name to version
        if: github.ref != 'refs/heads/main'
        run: |
          value=$(mvn $MAVEN_CLI_OPTS org.apache.maven.plugins:maven-help-plugin:3.1.1:evaluate -Dexpression=project.version -q -DforceStdout)
          branch_name="${GITHUB_REF#refs/heads/}"
          branch_name_formatted=$(echo "${branch_name}" | sed 's/[\\\/\:\"\<\>\|\?\*]/-/g')
          echo "value=$value-${branch_name_formatted}"
          mvn versions:set -DnewVersion=$value-${branch_name_formatted} -DgenerateBackupPoms=false

      - name: Maven Build
        id: mvn_build
        run: |
          value=$(mvn $MAVEN_CLI_OPTS org.apache.maven.plugins:maven-help-plugin:3.1.1:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn -DprimaryProvider=${{ inputs.destination_provider }} -B install deploy
          echo "Maven version: $value" >> $GITHUB_STEP_SUMMARY
