on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      SSO_URL:
        required: true
      ARTIFACTORY_DOCKERCONFIG:
        required: true
      ARGOCD_CERTIFICATE:
        required: true
      GRAFANA_CLIENT_ID:
        required: true
      GRAFANA_CLIENT_SECRET:
        required: true

name: Deploy Azure Infrastructure

env:
  TERRAFORM_VERSION: 1.4.4
  GITHUB_TOKEN: ${{ secrets.CIRCLE_CI_GITHUB_TOKEN }}
  TF_VAR_jv_project: ${{ vars.TF_VAR_JV_PROJECT}}
  TF_VAR_jv_name: ${{ vars.TF_VAR_JV_NAME}}
  ARM_USE_OIDC: true
  TF_VAR_grafana_client_id: ${{ secrets.GRAFANA_CLIENT_ID }}
  TF_VAR_grafana_client_secret: ${{ secrets.GRAFANA_CLIENT_SECRET }}

jobs:
  jv:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        data: ${{ fromJson(vars.AZURE_MATRIX) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform init
        id: init
        working-directory: terraform
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.SSH_KEY }}'
          terraform init -input=false -backend-config="resource_group_name=${TF_VAR_resource_group_name}" -backend-config="storage_account_name=${TF_VAR_storage_account_name}" -backend-config="container_name=${TF_VAR_container_name}"
          terraform workspace new "${{ matrix.data.ENVIRONMENT }}" || true
          terraform workspace select "${{ matrix.data.ENVIRONMENT }}"
        env:
          ARM_CLIENT_ID: ${{ matrix.data.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ matrix.data.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ matrix.data.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ matrix.data.ARM_SUBSCRIPTION_ID }}
          TF_VAR_location: ${{ matrix.data.AZURE_REGION }}
          TF_VAR_environment: ${{ matrix.data.ENVIRONMENT }}
          TF_VAR_resource_group_name: ${{ matrix.data.AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_storage_account_name: ${{ matrix.data.AZURE_STORAGE_ACCOUNT_NAME }}
          TF_VAR_container_name: ${{ matrix.data.AZURE_CONTAINER_NAME }}
          TF_VAR_docker_json_config: ${{ secrets.ARTIFACTORY_DOCKERCONFIG }}
          TF_VAR_sso_url: ${{ secrets.SSO_URL }}
          TF_VAR_argocd_certificate: ${{ secrets.ARGOCD_CERTIFICATE }}
          TF_VAR_github_ssh_key: ${{ secrets.SSH_KEY }}

      - name: Terraform Validate
        id: validate
        working-directory: terraform
        run: terraform validate -no-color
        env:
          TF_VAR_environment: ${{ matrix.data.ENVIRONMENT }}
      - name: Terraform Apply
        id: apply
        working-directory: terraform
        run: |
          terraform workspace list
          terraform apply -auto-approve -input=false -refresh=false
        env:
          TF_VAR_env: ${{ matrix.data.ENVIRONMENT }}
          TF_WORKSPACE: ${{ matrix.data.ENVIRONMENT }}
          ARM_CLIENT_ID: ${{ matrix.data.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ matrix.data.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ matrix.data.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ matrix.data.ARM_SUBSCRIPTION_ID }}
          TF_VAR_location: ${{ matrix.data.AZURE_REGION }}
          TF_VAR_environment: ${{ matrix.data.ENVIRONMENT }}
          TF_VAR_resource_group_name: ${{ matrix.data.AZURE_RESOURCE_GROUP_NAME }}
          TF_VAR_storage_account_name: ${{ matrix.data.AZURE_STORAGE_ACCOUNT_NAME }}
          TF_VAR_container_name: ${{ matrix.data.AZURE_CONTAINER_NAME }}
          TF_VAR_docker_json_config: ${{ secrets.ARTIFACTORY_DOCKERCONFIG }}
          TF_VAR_sso_url: ${{ secrets.SSO_URL }}
          TF_VAR_argocd_certificate: ${{ secrets.ARGOCD_CERTIFICATE }}
          TF_VAR_github_ssh_key: ${{ secrets.ARGOCD_PRIVATE_KEY }}
