---
name: Build for Pull Request

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build_and_tag:
    name: Build & Tag
    uses: nax-platform/github-actions/.github/workflows/build-deploy-maven.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{ secrets.UPDATE_MANIFEST_TOKEN }}
