name: DEV Environment Build

on:
  workflow_call:

jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Build
        run: |
          echo ${{ github.ref }}
      - name: Trigger Update Image Digest
        if: github.ref == 'refs/heads/main'
        run: |
          echo foo
