name: Update Image Digest

on:
  workflow_call:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-image-digest:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.event.client_payload.directory_name }}-${{ github.event.client_payload.environment_dir }}"
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Update image digest for Infra-Eks Managed Clusters (via SSH Auth)
        run: |
          export RUNTIME_DIRECTORY="kubernetes"
          mkdir -p ${{ github.workspace }}/${RUNTIME_DIRECTORY}/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          curl -s -o install_kustomize.sh "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
          chmod +x ./install_kustomize.sh; 
          ./install_kustomize.sh 5.1.0
          sudo mv kustomize /usr/local/bin/kustomize
          cd ${{ github.workspace }}/${RUNTIME_DIRECTORY}/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          if [ ! -f kustomization.yaml ]; then cat > kustomization.yaml << EndOfMessage
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization

          resources:
            - git@github.com:${{github.repository_owner}}/${{ github.event.client_payload.resource_directory_name || github.event.client_payload.directory_name }}/.platform/kubernetes/${{ github.event.client_payload.environment_dir }}
          EndOfMessage
          fi
          kustomize edit set image ${{ github.event.client_payload.image_name || github.event.client_payload.directory_name }}-server=naxgrp.jfrog.io/${{github.repository_owner}}-docker-local/applications/${{ github.event.client_payload.image_name || github.event.client_payload.directory_name }}-server@${{ github.event.client_payload.digest }}
          kustomize edit set annotation meta.naxgrp.com/github-repository:${{github.event.client_payload.repository}}
          kustomize edit set annotation meta.naxgrp.com/github-workflow-run-id:${{github.run_id}}-${{github.run_attempt}}
          git add .

      - name: Update image digest for Run Studio Managed Clusters (via HTTPS Auth)
        run: |
          export RUNTIME_DIRECTORY="run-studio"
          mkdir -p ${{ github.workspace }}/${RUNTIME_DIRECTORY}/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          curl -s -o install_kustomize.sh "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
          chmod +x ./install_kustomize.sh; 
          ./install_kustomize.sh 5.1.0
          sudo mv kustomize /usr/local/bin/kustomize
          cd ${{ github.workspace }}/${RUNTIME_DIRECTORY}/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          if [ ! -f kustomization.yaml ]; then cat > kustomization.yaml << EndOfMessage
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization

          resources:
            - https://github.com/${{github.repository_owner}}/${{ github.event.client_payload.resource_directory_name || github.event.client_payload.directory_name }}/.platform/kubernetes/${{ github.event.client_payload.environment_dir }}
          EndOfMessage
          fi
          kustomize edit set image ${{ github.event.client_payload.image_name || github.event.client_payload.directory_name }}-server=naxgrp.jfrog.io/${{github.repository_owner}}-docker-local/applications/${{ github.event.client_payload.image_name || github.event.client_payload.directory_name }}-server@${{ github.event.client_payload.digest }}
          kustomize edit set annotation meta.naxgrp.com/github-repository:${{github.event.client_payload.repository}}
          kustomize edit set annotation meta.naxgrp.com/github-workflow-run-id:${{github.run_id}}-${{github.run_attempt}}
          git add .

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "[skip ci] Update ${{ github.event.client_payload.directory_name }} image digest to ${{ github.event.client_payload.digest }}"
          git push origin main
