name: Update Image Digest

on:
  workflow_call:

jobs:
  update-image-digest:
    concurrency: update-kustomization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update image digest
        run: |
          mkdir -p ${{ github.workspace }}/kubernetes/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/kustomize
          cd ${{ github.workspace }}/kubernetes/${{ github.event.client_payload.directory_name }}/${{ github.event.client_payload.environment_dir }}
          if [ ! -f kustomization.yaml ]; then cat > kustomization.yaml << EndOfMessage
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization

          resources:
            - git@github.com:${{github.repository_owner}}/${{ github.event.client_payload.resource_directory_name || github.event.client_payload.directory_name }}/.platform/kubernetes/${{ github.event.client_payload.environment_dir }}
          EndOfMessage
          fi
          kustomize edit set image ${{ github.event.client_payload.directory_name }}-server=naxgrp.jfrog.io/${{ vars.TF_VAR_JV_PROJECT}}-${{ vars.TF_VAR_JV_NAME }}-docker-local/applications/${{ github.event.client_payload.directory_name }}-server@${{ github.event.client_payload.digest }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "[skip ci] Update ${{ github.event.client_payload.directory_name }} image digest to ${{ github.event.client_payload.digest }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
